export const inspirationTypes = {
  FETCH_INSPIRATON_CARDS_REQUEST: 'FETCH_INSPIRATON_CARDS_REQUEST',
  FETCH_INSPIRATON_CARDS_SUCCESS: 'FETCH_INSPIRATON_CARDS_SUCCESS',
  FETCH_INSPIRATON_CARDS_FAILURE: 'FETCH_INSPIRATON_CARDS_FAILURE',
  REMOVE_INSPIRATON_CARD: 'REMOVE_INSPIRATON_CARD',
  SORT_INSPIRATON_CARDS: 'SORT_INSPIRATON_CARDS',
};
