export const ideasTypes = {
  FETCH_IDEAS_ITEMS_REQUEST: 'FETCH_IDEAS_ITEMS_REQUEST',
  FETCH_IDEAS_ITEMS_SUCCESS: 'FETCH_IDEAS_ITEMS_SUCCESS',
  FETCH_IDEAS_ITEMS_FAILURE: 'FETCH_IDEAS_ITEMS_FAILURE',
};
